name: Deploy to Unraid
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
env:
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  GUILD_ID: ${{ secrets.GUILD_ID }}
  ADMIN_ID: ${{ secrets.ADMIN_ID }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  PIN_SERVER: ${{ secrets.PIN_SERVER }}
  PIN_CHANNEL: ${{ secrets.PIN_CHANNEL }}
  LASTFM_KEY: ${{ secrets.LASTFM_KEY }}
  LASTFM_SECRET: ${{ secrets.LASTFM_SECRET }}
  REBRICK_KEY: ${{ secrets.REBRICK_KEY }}
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: sicklesheen/smarmy:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Copy docker-compose.yml to remote server
        run: |
          sshpass -p ${{ secrets.UNRAID_PASSWORD }} scp -o StrictHostKeyChecking=no -P ${{ secrets.UNRAID_PORT }} docker-compose.yml root@${{ secrets.UNRAID_IP }}:/root/docker-compose.yml

      - name: Deploy to Unraid
        run: |
          sshpass -p ${{ secrets.UNRAID_PASSWORD }} ssh -tt -o StrictHostKeyChecking=no -p ${{ secrets.UNRAID_PORT }} root@${{ secrets.UNRAID_IP }} << EOF
          docker pull sicklesheen/smarmy:latest
          export BOT_TOKEN=${{ secrets.BOT_TOKEN }}
          export CLIENT_ID=${{ secrets.CLIENT_ID }}
          export GUILD_ID=${{ secrets.GUILD_ID }}
          export ADMIN_ID=${{ secrets.ADMIN_ID }}
          export DATABASE_URL=${{ secrets.DATABASE_URL }}
          export PIN_SERVER=${{ secrets.PIN_SERVER }}
          export PIN_CHANNEL=${{ secrets.PIN_CHANNEL }}
          export LASTFM_KEY=${{ secrets.LASTFM_KEY }}
          export LASTFM_SECRET=${{ secrets.LASTFM_SECRET }}
          export REBRICK_KEY=${{ secrets.REBRICK_KEY }}
          export CAT_KEY=${{ secrets.CAT_KEY }}
          export NASA_KEY=${{ secrets.NASA_KEY }}
          docker-compose -f /root/docker-compose.yml up -d
          exit
          EOF

      - name: Check if the app is running
        run: |
          sshpass -p ${{ secrets.UNRAID_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.UNRAID_PORT }} root@${{ secrets.UNRAID_IP }} docker ps | grep smarmy || exit 1

      - name: Clean up dangling Docker containers
        run: |
          sshpass -p ${{ secrets.UNRAID_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ secrets.UNRAID_PORT }} root@${{ secrets.UNRAID_IP }} docker rmi (docker images -f dangling=true -q)